<template>
    <UApp>
        <NuxtRouteAnnouncer/>
        <NuxtLoadingIndicator/>
        <NuxtLayout>
            <UMain>
                <NuxtPage/>
            </UMain>
        </NuxtLayout>
    </UApp>
</template>